title: Cindy Ripoll-Martinez
author:
  name: Cindy Ripoll-Martinez
  email: cnr53@miami.edu
description: > # this means to ignore newlines until "show_excerpts:"
  Bienenido a mi pagina personal. Soy una estudiante en la Universidad de Miami, con una especializacion en Psicologia y Español. Creo que el proposito de mi vida
  es ayudar al mundo a tráves de la menta. Por esta razón tengo planes de conseguir un doctoral en psicologia clinica. Aunque todavia estudio para obtener mi
  licensiatura, ya he trabajado en un laboratorio de neurociencías que se enfoca en los efectos de entrenamiento de la menta para mejorar la atencion. 

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
